# This script deploys your website automatically
name: Deploy

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [ main ]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our main branch
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build --if-present
    # Run our deployment command
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.